# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ClimaPlots
                                A QGIS plugin
 Indices Vegetativos
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                               -------------------
        begin                 : 2024-10-24
        copyright             : (C) 2024 by Caio Arantes
        email                 : github.com/caioarantes
        git sha               : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 * *
 * This program is free software; you can redistribute it and/or modify   *
 * it under the terms of the GNU General Public License as published by   *
 * the Free Software Foundation; either version 2 of the License, or      *
 * (at your option) any later version.                                    *
 * *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

from . import extlibs_manager

# Add extlibs to sys.path immediately so already-downloaded libraries are
# importable. The actual download (first run) happens in classFactory, where a
# QGIS interface exists to parent the progress dialog.
extlibs_manager.ensure_on_path()


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ClimaPlots class from file ClimaPlots.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    # ClimaPlots imports its scientific dependencies (xarray, pymannkendall,
    # pyhomogeneity, climdex, ...) eagerly at module load, so the external
    # libraries must be present before the import below. Download them on first
    # run, blocking until ready.
    if not extlibs_manager.ensure_ready(parent=iface.mainWindow()):
        raise RuntimeError(
            "ClimaPlots: external dependencies could not be downloaded. "
            "Check your internet connection and try reloading the plugin."
        )

    from .climaplots import ClimaPlots
    return ClimaPlots(iface)